apiVersion: tools.cosmos.network/v1
kind: Simulation
metadata:
  name: gaia-v3.0.0
spec:
  config:
    blocks: 10000
    period: 5
    timeout: 730h
    benchmark: true
    test: BenchmarkFullAppSimulation
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: 750m
        memory: 2Gi
  target:
    package: ./app
    repo: https://github.com/cosmos/gaia
    version: v3.0.0